export const MATERIALS = {
    'Wall': {
        type: 'Wall',
        isPassable: false,
        isPath: false,
        isVisited: false,
        borderEdges: {
            tl: false,
            tr: false,
            br: false,
            bl: false,
        },
        transitionDelay: 0,
        totalPathingDuration: 0,
    },
    'Player': {
        type: 'Player-Cell',
        isPassable: true,
        isPath: false,
        isVisited: false,
        borderEdges: {
            tl: true,
            tr: true,
            br: true,
            bl: true,
        },
        transitionDelay: 0,
        totalPathingDuration: 0,
    },
    'Goal': {
        type: 'Goal-Cell',
        isPassable: true,
        isPath: false,
        isVisited: false,
        borderEdges: {
            tl: false,
            tr: false,
            br: false,
            bl: false,
        },
        transitionDelay: 0,
        totalPathingDuration: 0,
    },
    'Empty-Cell': {
        type: 'Empty-Cell',
        isPassable: true,
        isPath: false,
        isVisited: false,
        borderEdges: {
            tl: true,
            tr: true,
            br: true,
            bl: true,
        },
        transitionDelay: 0,
        totalPathingDuration: 0,
    },
    'Water': {
        type: 'Water',
        isPassable: true,
        isPath: false,
        isVisited: false,
        borderEdges: {
            tl: false,
            tr: false,
            br: false,
            bl: false,
        },
        transitionDelay: 0,
        totalPathingDuration: 0,
    }
}
